name: bb-permission-granular-write-d459590809db49
on:
  workflow_dispatch:
permissions:
  actions: write
  contents: write
  packages: write
jobs:
  synthetic:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920
        with:
          egress-policy: audit
      - run: echo "bb-permission-granular-write-d459590809db49"
